### PR TITLE
Revert "Add famousbio.net to showcase"

### PR DESCRIPTION
**Pull request by leerob**
Reverts vercel/next-site#716

This site is not using Next.js.

### CODE REVIEW

**Review by lfades — APPROVED** [review]
Thanks!

**Comment by nguyenngocphuongnb** [comment]
image

Sorry for the late reply, but why do you think that famousbio.net is not built with Next.js?
You may not realize that Next.js is strong enough to customize almost things that you imagine.
I think the reason is that you can't find the element `#__NEXT_DATA__`. As i mentioned here: https://github.com/vercel/next-site/pull/716#issue-425747257, this site is `FULLY AMP` so this element is not necessary. We removed it from the cache handler

image

You may not merge my PR but you are wrong when saying "This site is not using Next.js."
@leerob @lfades

**Comment by lfades** [comment]
@nguyenngocphuongnb I requested a revert because the site wasn't working when the PR was merged.

In any case, we're currently not taking new sites as we expect to automate this in the future.

**Comment by nguyenngocphuongnb** [comment]
@lfades this reason is understandable than "This site is not using Next.js"
Thank you for replying me!

**Pull request merged**
