### PR TITLE
Make aside navigation (steps) more convenient in Learn section

### PR DESCRIPTION
**Pull request by eKhattak**
This PR is for https://github.com/vercel/next.js/issues/15776

Users will be able to show steps (Sub lessons) of the current lesson.

Desktop

Thanks to @lfades for giving clue.

### CODE REVIEW

**Comment by vasilii-kovalev** [comment]
Sorry, but is it intended that the sub-steps' names are not the same as appropriate pages' titles?

**Comment by eKhattak** [comment]
> Sorry, but is it intended that the substeps' names are not the same as appropriate pages' titles?

Do you mean to say that substeps' names are not the same as page titles? Can you please share a screenshot for more clarification.

**Comment by vasilii-kovalev** [comment]
Yes, exactly.

image

image

and so on...

**Comment by eKhattak** [comment]
Thanks, I'll fix those

**Comment by vasilii-kovalev** [comment]
Thanks for the update. Just noticed inconsistency in 3 places:
image
image
image

**Pull request merged**
